### ISSUE TITLE
Make this package compatible with latest Atom version

### ISSUE THREAD

**Issue by danielo515** [r24y/github-issues#30]
apm is complaining that there is no compatible version of this package for 1.0.19. Could you please make it compatible? Or at least provide a compatibility matrix on the readme.

Regards

**Comment by laughedelic** [comment]
+1

**Comment by r24y** [comment]
Thanks for the nudge. My apologies that this package is so far out of date.

I'm working on an update; expect something by this time next week, or else message me if I haven't closed this issue.

**Comment by TobiasBales** [comment]
Any update on this?

**Comment by ChristopherKing42** [comment]
:+1:
