### ISSUE TITLE
Shows empty issues list

### ISSUE THREAD

**Issue by laughedelic** [r24y/github-issues#33]
I get 

> No issues found

And a note about private-repos. But the repo is public and has a lot of issues: 

https://github.com/ohnosequences/loquat/issues

**Comment by r24y** [comment]
Is `ohnosequences/loquat` the only Git repository in the project tree? Right now if there are multiple repos then it'll only display issues for the first repo it finds (usually the first repo you opened).

**Comment by r24y** [comment]
Hi @laughedelic,

I just tested that repo against the new `v0.8.0` version and was able to see all of the issues. Try again and see if you're able to use the new version.

Closing this issue because I've verified your use case works now, but let me know if you still have issues.
