### ISSUE TITLE
Cannot load plug-in list on Windows behind proxy server

### ISSUE THREAD

**Issue by varosi** [r24y/github-issues#36]
Windows 8 x64
HTTP/HTTPS/Socks proxy

When I open Settings | Install I get:

> Fetching featured packages failed.Hide output…
> tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

I already have set proxy according to:
https://discuss.atom.io/t/how-to-install-an-atom-package-on-windows-8-behind-a-proxy-server/12520/2

**Comment by r24y** [comment]
Hi @varosi,

That's an issue with Atom, not this package. I'd suggest filing an issue on the [github/atom](https://github.com/atom/atom) repo if you're still affected by this, or seek help in the [forums](https://discuss.atom.io/).

**Comment by varosi** [comment]
Thanks!

**Comment by varosi** [comment]
This problem seems to be fixed in latest Atom. Thanks!
