### ISSUE TITLE
This 6-character program (bad_comment.idr) crashes Idris for atom

### ISSUE THREAD

**Issue by kevinsullivan** [r24y/github-issues#37]
{-
{-
-}

That's it.

The REPL gives this:

idris: user error (./bad_comment.idr:4:1: error: unexpected
    EOF, expected: end of comment
<EOF> 
^     )

**Comment by r24y** [comment]
What is Idris? How is this issue related to the `github-issues` Atom package?

**Comment by r24y** [comment]
Closing, since this seems unrelated to `github-issues`.
